version: "3"

services:

  
  #pgadmin4:
  #  image: dpage/pgadmin4
  #  container_name: visualizador_de_base_de_datos
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #    PGADMIN_DEFAULT_PASSWORD: "admin"
  #  ports:
  #    - "4000:80"
  #  depends_on:
  #    - postgres
  #  networks:
  #    nodes-networks:
  #      aliases:
  #        - visualizador_de_base_de_datos

  postgres:
    image: postgres
    container_name: sae_gestion_de_usuarios_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      nodes-networks:
        aliases:
          - sae_gestion_de_usuarios_db

  sae_gestion_de_usuarios_ms:
    build: .
    container_name: sae_gestion_de_usuarios_ms
    image: sae_gestion_de_usuarios_ms
    restart: always
    env_file:
      - .env
    ports:
      - "3021:8080"
    depends_on:
      - postgres
    networks:
      nodes-networks:
        aliases:
          - sae_gestion_de_usuarios_ms
    

volumes:
  postgres-data:

networks:
  nodes-networks:
    external: true
